version: '3.9'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      NODE_ENV: development
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
      DB_DATABASE: nestDB
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: admin12
      MINIO_SECRET_KEY: admin12-dev
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - database
      - minio

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nestDB
    ports:
      - '5431:5432'

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: admin12
      MINIO_ROOT_PASSWORD: admin12-dev
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
